package com.dt.beans;

import java.lang.reflect.Method;

import org.springframework.beans.factory.support.MethodReplacer;

public class ReportGeneratorReplacer implements MethodReplacer {

	public Object reimplement(Object obj, Method method, Object[] args) throws Throwable {
		// TODO Auto-generated method stub
		System.out.println(obj);
		String methodName = method.getName();
		System.out.println(methodName);
		if (methodName.equals("generate")) {

			System.out.println("Report generated by Aspose Api. reimplemented method..");
		}
		/*
		 * else if(methodName.equals("m1")) {
		 * System.out.println("Re implemented m1() method..."); }
		 */
		return obj;
	}

}
