package com.dt.beans;

public class ReportGenerator {

	public void generate() {
		System.out.println("Report Generated By POI Api  old method...");
	}

	public void generate(int i, int j) {
		System.out.println("ReportGenerator.generate()");
		System.out.println("Report Generated by Api....parameters");
	}

	public void generate(String s1, String s2) {
		System.out.println("ReportGenerator.generate() with String param");
	}

	public void m1() {
		System.out.println("old m1 method");
	}

	public void m1(String a, String b) {
		System.out.println("old m1(String a,String b) method");
	}
}// class
